services:
  db:
    image: postgres:16-bookworm
    container_name: faDb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fusionauth
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - faNetwork

  fa:
    image: fusionauth/fusionauth-app:latest
    container_name: fa
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://faDb:5432/fusionauth
      DATABASE_ROOT_USERNAME: postgres
      DATABASE_ROOT_PASSWORD: postgres
      DATABASE_USERNAME: fusionauth
      DATABASE_PASSWORD: fusionauth
      FUSIONAUTH_APP_MEMORY: 512M
      FUSIONAUTH_APP_RUNTIME_MODE: production
      FUSIONAUTH_APP_URL: http://local.fusionauth.io:9011
      SEARCH_TYPE: database
      FUSIONAUTH_APP_KICKSTART_FILE: /usr/local/fusionauth/kickstart/kickstart.json
    volumes:
      - ./kickstart.json:/usr/local/fusionauth/kickstart/kickstart.json
    ports:
      - "9011:9011"
    networks:
      - faNetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  faNetwork:
    driver: bridge
